import { createClient } from "npm:@supabase/supabase-js@2";
import { z } from "npm:zod@3.23.8";

import { corsHeaders } from "../_shared/cors.ts";

const BodySchema = z.object({
  businessAccountId: z.string().uuid(),
});

/**
 * Verifies a business email domain by looking for a TXT DNS record:
 *   TXT @  -> "naer-naering-verify=<token>"
 *
 * The token is generated by the payments-webhook when the business account
 * is created. The owner adds the TXT record at their DNS provider, then
 * triggers this function from the business panel.
 */
Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders(req) });
  }
  if (req.method !== "POST") {
    return new Response(JSON.stringify({ error: "Method not allowed" }), {
      status: 405,
      headers: { ...corsHeaders(req), "Content-Type": "application/json" },
    });
  }

  try {
    const authHeader = req.headers.get("Authorization");
    if (!authHeader?.startsWith("Bearer ")) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), {
        status: 401,
        headers: { ...corsHeaders(req), "Content-Type": "application/json" },
      });
    }
    const sbUser = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_ANON_KEY")!,
      { global: { headers: { Authorization: authHeader } } }
    );
    const token = authHeader.replace("Bearer ", "");
    const { data: claimsData, error: claimsErr } = await sbUser.auth.getClaims(token);
    if (claimsErr || !claimsData?.claims) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), {
        status: 401,
        headers: { ...corsHeaders(req), "Content-Type": "application/json" },
      });
    }
    const userId = claimsData.claims.sub as string;

    const parsed = BodySchema.safeParse(await req.json());
    if (!parsed.success) {
      return new Response(JSON.stringify({ error: "Invalid request" }), {
        status: 400,
        headers: { ...corsHeaders(req), "Content-Type": "application/json" },
      });
    }

    const sbAdmin = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!
    );

    const { data: account, error: accErr } = await sbAdmin
      .from("business_accounts")
      .select("id, owner_user_id, email_domain, domain_verification_token, domain_verified_at")
      .eq("id", parsed.data.businessAccountId)
      .maybeSingle();

    if (accErr || !account) {
      return new Response(JSON.stringify({ error: "Not found" }), {
        status: 404,
        headers: { ...corsHeaders(req), "Content-Type": "application/json" },
      });
    }

    if (account.owner_user_id !== userId) {
      return new Response(JSON.stringify({ error: "Forbidden" }), {
        status: 403,
        headers: { ...corsHeaders(req), "Content-Type": "application/json" },
      });
    }

    if (!account.email_domain || !account.domain_verification_token) {
      return new Response(
        JSON.stringify({ error: "Domain verification not configured for this account" }),
        { status: 400, headers: { ...corsHeaders(req), "Content-Type": "application/json" } }
      );
    }

    if (account.domain_verified_at) {
      return new Response(JSON.stringify({ verified: true, alreadyVerified: true }), {
        status: 200,
        headers: { ...corsHeaders(req), "Content-Type": "application/json" },
      });
    }

    // Look up TXT records via DoH (Cloudflare)
    const dohUrl = `https://cloudflare-dns.com/dns-query?name=${encodeURIComponent(
      account.email_domain
    )}&type=TXT`;
    const dohRes = await fetch(dohUrl, { headers: { Accept: "application/dns-json" } });
    if (!dohRes.ok) {
      return new Response(JSON.stringify({ error: "DNS lookup failed" }), {
        status: 502,
        headers: { ...corsHeaders(req), "Content-Type": "application/json" },
      });
    }
    const dohJson = await dohRes.json();
    const expected = `naer-naering-verify=${account.domain_verification_token}`;
    const records: string[] = (dohJson.Answer ?? []).map((r: { data: string }) =>
      r.data.replace(/^"|"$/g, "")
    );
    const match = records.some((r) => r.includes(expected));

    if (!match) {
      return new Response(
        JSON.stringify({
          verified: false,
          expected,
          foundRecords: records,
          help: `Legg til en TXT-record på @ for ${account.email_domain} med verdien "${expected}".`,
        }),
        { status: 200, headers: { ...corsHeaders(req), "Content-Type": "application/json" } }
      );
    }

    await sbAdmin
      .from("business_accounts")
      .update({ domain_verified_at: new Date().toISOString() })
      .eq("id", account.id);

    // Backfill seats for existing users with matching email
    const domainLower = account.email_domain.toLowerCase();
    const { data: existingUsers } = await sbAdmin.auth.admin.listUsers({ perPage: 1000 });
    const matching = (existingUsers?.users ?? []).filter(
      (u) => (u.email ?? "").toLowerCase().endsWith("@" + domainLower)
    );
    for (const u of matching) {
      await sbAdmin.from("business_seats").upsert(
        {
          business_account_id: account.id,
          user_id: u.id,
          email: u.email!,
          accepted_at: new Date().toISOString(),
          source: "domain_auto",
        },
        { onConflict: "business_account_id,email" }
      );
    }

    return new Response(JSON.stringify({ verified: true, backfilled: matching.length }), {
      status: 200,
      headers: { ...corsHeaders(req), "Content-Type": "application/json" },
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : "Unknown error";
    console.error("verify-business-domain error:", message);
    return new Response(JSON.stringify({ error: message }), {
      status: 500,
      headers: { ...corsHeaders(req), "Content-Type": "application/json" },
    });
  }
});